#!/bin/bash
#
#	virtual environment setup for generate_website
#

virtualenv .
source ./bin/activate
pip install inotify
pip install psutil
pip install opencv-contrib-python-headless
pip install paramiko
pip install numpy
pip install pillow
pip install scp

